name:       "mmmtl"
version:    0.0.0
author:     "Joe Kachmar"
copyright:  "2018 Joe Kachmar"
license:    Apache-2.0

extra-source-files: README.md

# cf. https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
ghc-options:
  - -fwarn-tabs
  - -fhide-source-paths
  - -fprint-potential-instances
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wcpp-undef
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wno-unused-do-bind
  - -Wno-deprecations
  - -Wno-monomorphism-restriction
  - -Wno-unticked-promoted-constructors
  - -Wpartial-fields

# cf. https://github.com/commercialhaskell/rio#language-extensions
default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  # - RecordWildCards # Explicitly disabled due to shadowing issues
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  # Standard libraries
  - base      >= 4.7   && < 5
  - protolude >= 0.2.2 && < 0.3

  - concurrency     >= 1.6.1.0  && < 1.7
  - dejafu          >= 1.11.0.3 && < 1.12
  - generic-lens    >= 1.0.0.2  && < 1.1
  - katip           >= 0.6.3.0  && < 0.7
  - lens            >= 4.16.1   && < 4.17
  - safe-exceptions >= 0.1.7.0  && < 0.2

library:
  source-dirs: library

executables:
  demo:
    main: Main.hs
    source-dirs: executables
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    # The only dependency required to build the executable is the library
    dependencies: mmmtl

tests:
  tasty:
    main: Driver.hs
    source-dirs: test
    dependencies:
      - mmmtl

      - tasty          >= 1.1.0.4 && < 1.2
      - tasty-discover >= 4.2.1   && < 4.3
      - tasty-hspec    >= 1.1.5   && < 1.2

    # Tasty does not support sequential tests in threaded mode
    # ghc-options:
    #   - -threaded
    #   - -rtsopts
    #   - -with-rtsopts=-N
